<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>