<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ConfKit\ConfKit.csproj" />
  </ItemGroup>
</Project>