<Project>
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageProjectUrl>https://github.com/huoshan12345/ConfKit</PackageProjectUrl>
    <PackageTags>ini;parser</PackageTags>
    <Authors>huoshan12345</Authors>
    <RepositoryUrl>https://github.com/huoshan12345/ConfKit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Copyright>huoshan12345</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
    <IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
    <TargetFrameworkVersion>$([MSBuild]::GetTargetFrameworkVersion($(TargetFramework), 2))</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="$(IsWindows)">$(TargetFrameworks);net472;</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" Visible="false"/>
    <None Include="$(MSBuildThisFileDirectory)..\LICENSE.TXT" Pack="true" PackagePath="\" Visible="false"/>
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>